# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-20 03:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semi_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(default='email@email.com', max_length=255),
        ),
    ]
